// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcricYdP1Lvr49lYPC1-BtvGPPkSoycfI',
    appId: '1:944518007403:web:d03a73eaace6c261373f2e',
    messagingSenderId: '944518007403',
    projectId: 'smart-tourism-iq',
    authDomain: 'smart-tourism-iq.firebaseapp.com',
    storageBucket: 'smart-tourism-iq.firebasestorage.app',
    measurementId: 'G-FNXZ0F806E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Xfx13pCCD3BSOupB-MXQNsAFXeaswhk',
    appId: '1:944518007403:android:4e3f80def98750c7373f2e',
    messagingSenderId: '944518007403',
    projectId: 'smart-tourism-iq',
    storageBucket: 'smart-tourism-iq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0i7YZvJ1P0xSAnaCAvpL-JFMRGg4KdXo',
    appId: '1:944518007403:ios:354de49434510743373f2e',
    messagingSenderId: '944518007403',
    projectId: 'smart-tourism-iq',
    storageBucket: 'smart-tourism-iq.firebasestorage.app',
    iosBundleId: 'com.example.smartTourismIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0i7YZvJ1P0xSAnaCAvpL-JFMRGg4KdXo',
    appId: '1:944518007403:ios:354de49434510743373f2e',
    messagingSenderId: '944518007403',
    projectId: 'smart-tourism-iq',
    storageBucket: 'smart-tourism-iq.firebasestorage.app',
    iosBundleId: 'com.example.smartTourismIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcricYdP1Lvr49lYPC1-BtvGPPkSoycfI',
    appId: '1:944518007403:web:1d7a30a7f99584d3373f2e',
    messagingSenderId: '944518007403',
    projectId: 'smart-tourism-iq',
    authDomain: 'smart-tourism-iq.firebaseapp.com',
    storageBucket: 'smart-tourism-iq.firebasestorage.app',
    measurementId: 'G-4SG2WF0V01',
  );
}
